// This file is autogenerated by github.com/gonum/unit/autogen
// Changes should be made to the autogenerated template rather than this one

// Copyright ©2014 The gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package unit

import (
	"errors"
	"fmt"
	"math"
)

// Acceleration represents an acceleration in meters per second squared
type Acceleration float64

const (
	YottaMPSSq Acceleration = 1e24
	ZettaMPSSq Acceleration = 1e21
	ExaMPSSq   Acceleration = 1e18
	PetaMPSSq  Acceleration = 1e15
	TeraMPSSq  Acceleration = 1e12
	GigaMPSSq  Acceleration = 1e9
	MegaMPSSq  Acceleration = 1e6
	KiloMPSSq  Acceleration = 1e3
	HectoMPSSq Acceleration = 1e2
	DecaMPSSq  Acceleration = 1e1
	MPSSq      Acceleration = 1.0
	DeciMPSSq  Acceleration = 1e-1
	CentiMPSSq Acceleration = 1e-2
	MilliMPSSq Acceleration = 1e-3
	MicroMPSSq Acceleration = 1e-6
	NanoMPSSq  Acceleration = 1e-9
	PicoMPSSq  Acceleration = 1e-12
	FemtoMPSSq Acceleration = 1e-15
	AttoMPSSq  Acceleration = 1e-18
	ZeptoMPSSq Acceleration = 1e-21
	YoctoMPSSq Acceleration = 1e-24
)

// Unit converts the Acceleration to a *Unit
func (a Acceleration) Unit() *Unit {
	return New(float64(a), Dimensions{
		LengthDim: -1,
		TimeDim:   -2,
	})
}

// Acceleration allows Acceleration to implement a Accelerationer interface
func (a Acceleration) Acceleration() Acceleration {
	return a
}

// From converts the unit into the receiver. From returns an
// error if there is a mismatch in dimension
func (a *Acceleration) From(u Uniter) error {
	if !DimensionsMatch(u, MPSSq) {
		*a = Acceleration(math.NaN())
		return errors.New("Dimension mismatch")
	}
	*a = Acceleration(u.Unit().Value())
	return nil
}

func (a Acceleration) Format(fs fmt.State, c rune) {
	switch c {
	case 'v':
		if fs.Flag('#') {
			fmt.Fprintf(fs, "%T(%v)", a, float64(a))
			return
		}
		fallthrough
	case 'e', 'E', 'f', 'F', 'g', 'G':
		p, pOk := fs.Precision()
		if !pOk {
			p = -1
		}
		w, wOk := fs.Width()
		if !wOk {
			w = -1
		}
		fmt.Fprintf(fs, "%*.*"+string(c), w, p, float64(a))
		fmt.Fprint(fs, " m/s^2")
	default:
		fmt.Fprintf(fs, "%%!%c(%T=%g m/s^2)", c, a, float64(a))
		return
	}
}
