// This file is autogenerated by github.com/gonum/unit/autogen
// Changes should be made to the autogenerated template rather than this one

// Copyright ©2014 The gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package unit

import (
	"errors"
	"fmt"
	"math"
)

// Capacitance represents an electric capacitance in farads
type Capacitance float64

const (
	Yottafarad Capacitance = 1e24
	Zettafarad Capacitance = 1e21
	Exafarad   Capacitance = 1e18
	Petafarad  Capacitance = 1e15
	Terafarad  Capacitance = 1e12
	Gigafarad  Capacitance = 1e9
	Megafarad  Capacitance = 1e6
	Kilofarad  Capacitance = 1e3
	Hectofarad Capacitance = 1e2
	Decafarad  Capacitance = 1e1
	Farad      Capacitance = 1.0
	Decifarad  Capacitance = 1e-1
	Centifarad Capacitance = 1e-2
	Millifarad Capacitance = 1e-3
	Microfarad Capacitance = 1e-6
	Nanofarad  Capacitance = 1e-9
	Picofarad  Capacitance = 1e-12
	Femtofarad Capacitance = 1e-15
	Attofarad  Capacitance = 1e-18
	Zeptofarad Capacitance = 1e-21
	Yoctofarad Capacitance = 1e-24
)

// Unit converts the Capacitance to a *Unit
func (ca Capacitance) Unit() *Unit {
	return New(float64(ca), Dimensions{
		CurrentDim: 2,
		LengthDim:  -2,
		MassDim:    -1,
		TimeDim:    4,
	})
}

// Capacitance allows Capacitance to implement a Capacitanceer interface
func (ca Capacitance) Capacitance() Capacitance {
	return ca
}

// From converts the unit into the receiver. From returns an
// error if there is a mismatch in dimension
func (ca *Capacitance) From(u Uniter) error {
	if !DimensionsMatch(u, Farad) {
		*ca = Capacitance(math.NaN())
		return errors.New("Dimension mismatch")
	}
	*ca = Capacitance(u.Unit().Value())
	return nil
}

func (ca Capacitance) Format(fs fmt.State, c rune) {
	switch c {
	case 'v':
		if fs.Flag('#') {
			fmt.Fprintf(fs, "%T(%v)", ca, float64(ca))
			return
		}
		fallthrough
	case 'e', 'E', 'f', 'F', 'g', 'G':
		p, pOk := fs.Precision()
		if !pOk {
			p = -1
		}
		w, wOk := fs.Width()
		if !wOk {
			w = -1
		}
		fmt.Fprintf(fs, "%*.*"+string(c), w, p, float64(ca))
		fmt.Fprint(fs, " F")
	default:
		fmt.Fprintf(fs, "%%!%c(%T=%g F)", c, ca, float64(ca))
		return
	}
}
