// This file is autogenerated by github.com/gonum/unit/autogen
// Changes should be made to the autogenerated template rather than this one

// Copyright ©2014 The gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package unit

import (
	"errors"
	"fmt"
	"math"
)

// ElecPoten represents an electric potential in Volts
type ElecPoten float64

const (
	Yottavolt ElecPoten = 1e24
	Zettavolt ElecPoten = 1e21
	Exavolt   ElecPoten = 1e18
	Petavolt  ElecPoten = 1e15
	Teravolt  ElecPoten = 1e12
	Gigavolt  ElecPoten = 1e9
	Megavolt  ElecPoten = 1e6
	Kilovolt  ElecPoten = 1e3
	Hectovolt ElecPoten = 1e2
	Decavolt  ElecPoten = 1e1
	Volt      ElecPoten = 1.0
	Decivolt  ElecPoten = 1e-1
	Centivolt ElecPoten = 1e-2
	Millivolt ElecPoten = 1e-3
	Microvolt ElecPoten = 1e-6
	Nanovolt  ElecPoten = 1e-9
	Picovolt  ElecPoten = 1e-12
	Femtovolt ElecPoten = 1e-15
	Attovolt  ElecPoten = 1e-18
	Zeptovolt ElecPoten = 1e-21
	Yoctovolt ElecPoten = 1e-24
)

// Unit converts the ElecPoten to a *Unit
func (e ElecPoten) Unit() *Unit {
	return New(float64(e), Dimensions{
		CurrentDim: 1,
	})
}

// ElecPoten allows ElecPoten to implement a ElecPotener interface
func (e ElecPoten) ElecPoten() ElecPoten {
	return e
}

// From converts the unit into the receiver. From returns an
// error if there is a mismatch in dimension
func (e *ElecPoten) From(u Uniter) error {
	if !DimensionsMatch(u, Volt) {
		*e = ElecPoten(math.NaN())
		return errors.New("Dimension mismatch")
	}
	*e = ElecPoten(u.Unit().Value())
	return nil
}

func (e ElecPoten) Format(fs fmt.State, c rune) {
	switch c {
	case 'v':
		if fs.Flag('#') {
			fmt.Fprintf(fs, "%T(%v)", e, float64(e))
			return
		}
		fallthrough
	case 'e', 'E', 'f', 'F', 'g', 'G':
		p, pOk := fs.Precision()
		if !pOk {
			p = -1
		}
		w, wOk := fs.Width()
		if !wOk {
			w = -1
		}
		fmt.Fprintf(fs, "%*.*"+string(c), w, p, float64(e))
		fmt.Fprint(fs, " V")
	default:
		fmt.Fprintf(fs, "%%!%c(%T=%g V)", c, e, float64(e))
		return
	}
}
