// This file is autogenerated by github.com/gonum/unit/autogen
// Changes should be made to the autogenerated template rather than this one

// Copyright ©2014 The gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package unit

import (
	"errors"
	"fmt"
	"math"
)

// Velocity represents a velocity in meters per second
type Velocity float64

// Unit converts the Velocity to a *Unit
func (v Velocity) Unit() *Unit {
	return New(float64(v), Dimensions{
		LengthDim: 1,
		TimeDim:   -1,
	})
}

// Velocity allows Velocity to implement a Velocityer interface
func (v Velocity) Velocity() Velocity {
	return v
}

// From converts the unit into the receiver. From returns an
// error if there is a mismatch in dimension
func (v *Velocity) From(u Uniter) error {
	if !DimensionsMatch(u) {
		*v = Velocity(math.NaN())
		return errors.New("Dimension mismatch")
	}
	*v = Velocity(u.Unit().Value())
	return nil
}

func (v Velocity) Format(fs fmt.State, c rune) {
	switch c {
	case 'v':
		if fs.Flag('#') {
			fmt.Fprintf(fs, "%T(%v)", v, float64(v))
			return
		}
		fallthrough
	case 'e', 'E', 'f', 'F', 'g', 'G':
		p, pOk := fs.Precision()
		if !pOk {
			p = -1
		}
		w, wOk := fs.Width()
		if !wOk {
			w = -1
		}
		fmt.Fprintf(fs, "%*.*"+string(c), w, p, float64(v))
		fmt.Fprint(fs, " m/s")
	default:
		fmt.Fprintf(fs, "%%!%c(%T=%g m/s)", c, v, float64(v))
		return
	}
}
