// This file is autogenerated by github.com/gonum/unit/autogen
// Changes should be made to the autogenerated template rather than this one

// Copyright ©2014 The gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package unit

import (
	"errors"
	"fmt"
	"math"
)

// ElecPoten represents an electric potential in Volts
type Voltage float64

const (
	Yottavolt Voltage = 1e24
	Zettavolt Voltage = 1e21
	Exavolt   Voltage = 1e18
	Petavolt  Voltage = 1e15
	Teravolt  Voltage = 1e12
	Gigavolt  Voltage = 1e9
	Megavolt  Voltage = 1e6
	Kilovolt  Voltage = 1e3
	Hectovolt Voltage = 1e2
	Decavolt  Voltage = 1e1
	Volt      Voltage = 1.0
	Decivolt  Voltage = 1e-1
	Centivolt Voltage = 1e-2
	Millivolt Voltage = 1e-3
	Microvolt Voltage = 1e-6
	Nanovolt  Voltage = 1e-9
	Picovolt  Voltage = 1e-12
	Femtovolt Voltage = 1e-15
	Attovolt  Voltage = 1e-18
	Zeptovolt Voltage = 1e-21
	Yoctovolt Voltage = 1e-24
)

// Unit converts the Voltage to a *Unit
func (e Voltage) Unit() *Unit {
	return New(float64(e), Dimensions{
		CurrentDim: -1,
		LengthDim:  2,
		MassDim:    1,
		TimeDim:    -3,
	})
}

// Voltage allows Voltage to implement a Voltageer interface
func (e Voltage) Voltage() Voltage {
	return e
}

// From converts the unit into the receiver. From returns an
// error if there is a mismatch in dimension
func (e *Voltage) From(u Uniter) error {
	if !DimensionsMatch(u, Volt) {
		*e = Voltage(math.NaN())
		return errors.New("Dimension mismatch")
	}
	*e = Voltage(u.Unit().Value())
	return nil
}

func (e Voltage) Format(fs fmt.State, c rune) {
	switch c {
	case 'v':
		if fs.Flag('#') {
			fmt.Fprintf(fs, "%T(%v)", e, float64(e))
			return
		}
		fallthrough
	case 'e', 'E', 'f', 'F', 'g', 'G':
		p, pOk := fs.Precision()
		if !pOk {
			p = -1
		}
		w, wOk := fs.Width()
		if !wOk {
			w = -1
		}
		fmt.Fprintf(fs, "%*.*"+string(c), w, p, float64(e))
		fmt.Fprint(fs, " V")
	default:
		fmt.Fprintf(fs, "%%!%c(%T=%g V)", c, e, float64(e))
		return
	}
}
